development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: db-dev
  pool: 5
  username: roland
  password: freedom
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: db-test
  pool: 5
  username: roland
  password: freedom
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: db-produce
  pool: 5
  username: root
  password: